apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: "{{ .Values.branchName }}.{{ .Values.domain }}"
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
